# Project: Proyecto 1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main2.o $(RES)
LINKOBJ  = main2.o $(RES)
LIBS =  -L"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/lib"  
INCS =  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"E:/HECTOR/Guias inacap/Dev-C++/Dev-CppPortable/App/devcpp/include" 
BIN  = "Proyecto 1.exe"
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "Proyecto 1.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Proyecto 1.exe" $(LIBS)

main2.o: main2.c
	$(CC) -c main2.c -o main2.o $(CFLAGS)
