gcc ex12bit.c -o ex12bit.exe -lalleg
gcc ex3buf.c -o ex3buf.exe -lalleg
gcc ex3d.c -o ex3d.exe -lalleg
gcc exaccel.c -o exaccel.exe -lalleg
gcc exalpha.c -o exalpha.exe -lalleg
gcc exbitmap.c -o exbitmap.exe -lalleg
gcc exblend.c -o exblend.exe -lalleg
gcc excamera.c -o excamera.exe -lalleg
gcc excolmap.c -o excolmap.exe -lalleg
gcc exconfig.c -o exconfig.exe -lalleg
gcc excustom.c -o excustom.exe -lalleg
gcc exdata.c -o exdata.exe -lalleg
gcc exdbuf.c -o exdbuf.exe -lalleg
gcc exexedat.c -o exexedat.exe -lalleg
gcc exfixed.c -o exfixed.exe -lalleg
gcc exflame.c -o exflame.exe -lalleg
gcc exflip.c -o exflip.exe -lalleg
gcc exfont.c -o exfont.exe -lalleg
gcc exgui.c -o exgui.exe -lalleg
gcc exhello.c -o exhello.exe -lalleg
gcc exjoy.c -o exjoy.exe -lalleg
gcc exkeys.c -o exkeys.exe -lalleg
gcc exlights.c -o exlights.exe -lalleg
gcc exmem.c -o exmem.exe -lalleg
gcc exmidi.c -o exmidi.exe -lalleg
gcc exmouse.c -o exmouse.exe -lalleg
gcc expackf.c -o expackf.exe -lalleg
gcc expal.c -o expal.exe -lalleg
gcc expat.c -o expat.exe -lalleg
gcc exquat.c -o exquat.exe -lalleg
gcc exrgbhsv.c -o exrgbhsv.exe -lalleg
gcc exrotscl.c -o exrotscl.exe -lalleg
gcc exsample.c -o exsample.exe -lalleg
gcc exscale.c -o exscale.exe -lalleg
gcc exscn3d.c -o exscn3d.exe -lalleg
gcc exscroll.c -o exscroll.exe -lalleg
gcc exshade.c -o exshade.exe -lalleg
gcc exspline.c -o exspline.exe -lalleg
gcc exsprite.c -o exsprite.exe -lalleg
gcc exstars.c -o exstars.exe -lalleg
gcc exstream.c -o exstream.exe -lalleg
gcc exswitch.c -o exswitch.exe -lalleg
gcc exsyscur.c -o exsyscur.exe -lalleg
gcc extimer.c -o extimer.exe -lalleg
gcc extrans.c -o extrans.exe -lalleg
gcc extrans2.c -o extrans2.exe -lalleg
gcc extruec.c -o extruec.exe -lalleg
gcc exunicod.c -o exunicod.exe -lalleg
gcc exupdate.c -o exupdate.exe -lalleg
gcc exxfade.c -o exxfade.exe -lalleg
gcc exzbuf.c -o exzbuf.exe -lalleg
